AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/tasks/**/*.rake
  Exclude:
    - vendor/**/*
    - bin/**/*

  UseCache: true
  CacheRootDirectory: 'cache/'
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Style/FileName:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Severity: warning
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/ClassLength:
  Max: 200